services:
  - type: web
    name: molodezh-dashboard
    runtime: python
    buildCommand: |
      cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PORT
        value: 8002
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
